export const NATIONALITIES = {
  AU: "Australia",
  BR: "Brazil",
  CA: "Canada",
  CH: "Switzerland",
  DE: "Germany",
  DK: "Denmark",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  IE: "Ireland",
  IR: "Iran",
  NO: "Norway",
  NL: "Netherlands",
  NZ: "New Zealand",
  TR: "Turkey",
  US: "United States",
};
